@address = Pruimengaarde 8, Houten, Netherlands
@zoom = 18
@size = 800x600

### Get static map image URL for the address
# @name getMap
GET {{BaseUrl}}/api/user/maps/image?address={{address}}&zoom={{zoom}}&size={{size}}
Accept: application/json
