
#
## Setup Address Folder (from Angular app - proxied)
# When calling from Angular app running on port 49806, use the proxied path

POST {{BaseUrl}}/api/folders-and-files?addressFolderId={{AddressFolderId}}
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###

### Get Folder Structure
# Gets the hierarchical folder and file structure from Google Drive

GET {{BaseUrl}}/api/folders-and-files/structure
Authorization: Bearer {{AccessToken}}

###

### Get Files (Flat List)
# Gets a flat list of all files from Google Drive folder

GET {{BaseUrl}}/api/folders-and-files/files
Authorization: Bearer {{AccessToken}}

###

### Get Files from Specific Folder
# Gets files from a specific folder ID

GET {{BaseUrl}}/api/folders-and-files/files?folderId={{AddressFolderId}}
Authorization: Bearer {{AccessToken}}

###

### Get Image by File ID
# Gets a specific image file by its file ID

@ImageFileId=1WhM09OSSWFh8MZPPkxYjR-J6CdKQzui5

GET {{BaseUrl}}/api/folders-and-files/image?fileId={{ImageFileId}}
Authorization: Bearer {{AccessToken}}

###
